name: Deploy Static Website (Reusable)

on:
  workflow_call:
    inputs:
      source-folder:
        required: true
        type: string
      destination-folder:
        required: true
        type: string
    secrets:
      AZURE_STORAGE_ACCOUNT:
        required: true
      AZURE_STORAGE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Blob
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Deploying ${{ inputs.source-folder }} to ${{ inputs.destination-folder }} in $web..."
            az storage blob upload-batch \
              --source ${{ inputs.source-folder }} \
              --destination "$web/${{ inputs.destination-folder }}" \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
              --overwrite
